name: 自动打卡

on:
#   schedule:
#     - cron: '0 0 * * *' # 每天在国际标准时间0点（北京时间8点）运行
  workflow_dispatch: # 手动运行工作流程

jobs:
  build:

    # 系统环境
    runs-on: ubuntu-latest

    # 执行步骤
    steps:

    # 拉取当前github文件
    - name: 拉取文件
      uses: actions/checkout@v2
    
    # 配置node环境
    - name: 配置node环境
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    

    # 配置环境变量给js读取，执行js文件
    - name: 运行任务
      env:
        INFO: ${{ secrets.INFO }}
        MAIL: ${{ secrets.MAIL }}
      run: node index.js
                
